### PR TITLE
Issue 288

### PR DESCRIPTION
**Pull request by sw4n**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Has tests?    | no
| Fixed tickets | #288

### CODE REVIEW

**Comment by tolry** [comment]
I do not know this part of the bundle at all, but the docblock states that `@param string $id Comma separated list of identifiers`

Anybody around who knows these bundle controllers and can tell us, if there are use cases with multiple ids? @DavidBadura @smoench @bendavies @andrewtch  ...?

Explode on a single number (or string containing a single number) should not be the problem here (https://3v4l.org/jLdJA)

As you mentioned in #288 this seems to be the faulty logic https://github.com/simplethings/EntityAuditBundle/blob/master/src/SimpleThings/EntityAudit/AuditReader.php#L175 expecting the first key in the array/hashmap to be the column name(??)

Judging from the obvious problem when using the bundle actions I would say, nobody could use them without error right now. If I do not get any objections, I will merge this.

**Comment by DavidBadura** [comment]
@tolry The usecase of multiple ids is multiple primary keys ;-) You don't have in this case only one id. 

@sw4n you should check after exploding if you have only one element in the array and then pass the one element instead of the array.

**Comment by tolry** [comment]
@DavidBadura ok, but explode still leaves you with numeric keys to the hashmap which cannot work properly the way the AuditReader deals with array for `$id`

**Comment by tolry** [comment]
@DavidBadura just to make sure, with "multiple ids" you mean compound primary keys, right?

**Comment by sw4n** [comment]
@DavidBadura I agree with @tolry in case of several primary keys, after explode the keys are stay numeric and can't be used in reader. 
Also, I must say that this pull request must be deleted or declined, because it's made from master, but not from stable version. I can make a fix, after proper deciding what to do.

**Comment by nicolas-san** [comment]
Hi guys, any news on this ?
Thanks :)

**Pull request closed without merging**
