### PR TITLE
Add "type": "symfony-bundle" in composer file

### PR DESCRIPTION
**Pull request by anacona16**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Has tests?    | no

This allow to Symfony Flex to enable it on bundles.php

### CODE REVIEW

**Comment by dunglas** [comment]
@gimler sorry but I'm not the maintainer of this bundle, and I don't own any right on it.

**Comment by tolry** [comment]
situation:

* master is currently in the process of splitting the project up in library + symfony-bundle, master is currently not usable (any ETA @DavidBadura?)
* maintenance: almost non existent, I am a bit of the last man standing here and have no knowledge of the inner code base (see previous discussion on this topic, if interested https://github.com/simplethings/EntityAuditBundle/issues/203)

if you create a PR against 1.x-branch I will merge it and publish a release

**Comment by anacona16** [comment]
New PR is here #313 closing this.

**Comment by tolry** [comment]
see https://github.com/simplethings/EntityAuditBundle/releases/tag/v1.0.7

**Pull request closed without merging**
